---
version: 2
project_name: jdownloader-cli
release:
  github:
    owner: rkosegi
    name: jdownloader-cli
  name_template: '{{.Tag}}'
builds:
  - id: jdownloader-cli
    targets:
      - linux_amd64_v1
      - linux_arm64
      - darwin_amd64_v1
      - darwin_arm64
      - windows_amd64_v1
      - windows_arm64
    dir: .
    main: cmd/cli.go
    binary: jdownloader-cli
    ldflags:
      - -s -w
      - -X github.com/rkosegi/jdownloader-cli/internal.Version={{.Version}}
      - -X github.com/rkosegi/jdownloader-cli/internal.Revision={{.Commit}}
      - -X github.com/rkosegi/jdownloader-cli/internal.Branch={{.Tag}}
      - -X github.com/rkosegi/jdownloader-cli/internal.BuildDate={{.Date}}
      - -X github.com/rkosegi/jdownloader-cli/internal.BuildUser={{.Env.USER}}
